---
apiVersion: v1
kind: Service
metadata:
  name: social-graph-service
  labels:
    death-star-project: social-network
    app: social-graph-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: social-graph-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-service
  labels:
    death-star-project: social-network
    app: social-graph-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: social-graph-service
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: social-graph-service
      name: social-graph-service
    spec:
      containers:
      - name: social-graph-service
        image: deathstarbench/social-network-microservices
        command: ["SocialGraphService"]
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
