---
apiVersion: v1
kind: Service
metadata:
  name: url-shorten-mongodb
  labels:
    death-star-project: social-network
    app: url-shorten-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app: url-shorten-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shorten-mongodb
  labels:
    death-star-project: social-network
    app: url-shorten-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: url-shorten-mongodb
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: url-shorten-mongodb
      name: url-shorten-mongodb
    spec:
      containers:
      - name: url-shorten-mongodb
        image: mongo:4.4.6
        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
      restartPolicy: Always
      volumes:
      - name: my-data
        emptyDir: {}
