apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rest-service-timeout
spec:
  destination:
    name: rest-service-2
  route:
  - labels:
      version: v1
  httpReqTimeout:
    simpleTimeout:
      timeout: 5s
