# helm install redis-post bitnami/redis-cluster -n yanqizhang --set global.storageClass=local-storage --set persistence.size=20Gi --set global.redis.password=redispost --set cluster.nodes=6
# helm install redis-post bitnami/redis-cluster -n yanqizhang \
# --set global.storageClass=local-storage \
# --set persistence.size=20Gi \
# --set global.redis.password=redispost
# --set cluster.nodes=6

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: post-store
  namespace: yanqizhang
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisType
    value: cluster
  - name: redisHost
    value: redis-post-redis-cluster:6379
  - name: redisPassword
    value: redispost
  - name: keyPrefix
    value: none
