# helm install redis-post bitnami/redis -n yanqizhang --set global.storageClass=local-storage --set master.persistence.size=10Gi --set replica.persistence.size=10Gi --set global.redis.password=redispost
# helm install redis-post bitnami/redis -n yanqizhang \
# --set global.storageClass=local-storage \
# --set master.persistence.size=10Gi \
# --set replica.persistence.size=10Gi \
# --set global.redis.password=redispost
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: post-store
  namespace: yanqizhang
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-post-master:6379
  - name: redisPassword
    value: redispost
  - name: keyPrefix
    value: none
