apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    receivers:
    - name: default-receiver
      email_configs:
      - to: 'xxxxxxxxxxxx@126.com'
    - name: alertsnitch
      webhook_configs:
        - url: http://alertsnitch:9567/webhook

    route:
      group_interval: 5m # 如果组内内容不变化，合并为一条警报信息，5m后发送。
      group_wait: 30s # 在组内等待所配置的时间，如果同组内，30秒内出现相同报警，在一个组内出现。
      receiver: default-receiver
      repeat_interval: 24h # 发送报警间隔，如果指定时间内没有修复，则重新发送报警。
      group_by: [alertname]  # 报警分组
      routes:
      - receiver: default-receiver
        continue: true
      - receiver: alertsnitch
        continue: true
