apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertsnitch-mysql
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: alertsnitch-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: alertsnitch-mysql
    spec:
      containers:
      - name: alertsnitch-mysql
        image: 569107519/alertsnitch-mysql:v1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: alertsnitch
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
            
---

apiVersion: v1
kind: Service
metadata:
  name: alertsnitch-mysql
  namespace: kube-system
spec:
  ports:
    - port: 3306
  selector:
   app: alertsnitch-mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertsnitch
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertsnitch    
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertsnitch
    spec:
      containers:
      - image: registry.gitlab.com/yakshaving.art/alertsnitch
        name: alertsnitch
        ports:
        - containerPort: 9567
          name: http
        env:
        - name: ALERTSNITCH_BACKEND
          value: mysql
        - name: ALERTSNITCH_DSN
          value: root:root@tcp(alertsnitch-mysql:3306)/alertsnitch
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9567
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /-/health
            port: 9567
          initialDelaySeconds: 60
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: alertsnitch
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 9567
    targetPort: http
  selector:
    app.kubernetes.io/name: alertsnitch
