{{- $root := . }}
{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svc.name }}
type: Opaque
stringData:
  {{- $envNamePrefix := $svc.name | trimPrefix "ts-" | trimSuffix "-service" | replace "-" "_" | upper }}
  {{ $envNamePrefix }}_MYSQL_HOST: "{{ $root.Values.mysql.host }}"
  {{ $envNamePrefix }}_MYSQL_PORT: "{{ $root.Values.mysql.port }}"
  {{ $envNamePrefix }}_MYSQL_DATABASE: "{{ $root.Values.mysql.database }}"
  {{ $envNamePrefix }}_MYSQL_USER: "{{ $root.Values.mysql.user }}"
  {{ $envNamePrefix }}_MYSQL_PASSWORD: "{{ $root.Values.mysql.password }}"
---
{{- end }}
