{{- $root := . }}
{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  labels:
    app: {{ $svc.name }}
spec:
  {{- with $svc.type }}
  type: {{ $svc.type }}
  {{- end}}
  ports:
    - port: {{ $root.Values.global.port }}
      {{- with $svc.targetPort }}
      targetPort: {{ $svc.targetPort }}
      {{- end}}
      {{- if $svc.nodePort }}
      nodePort: {{ $svc.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    app: {{ $svc.name }}
---
{{- end}}