spring:
  application:
    name: ts-consign-service
  data:
    mongodb:
      host: ts-consign-mongo
      database: ts
      port: 27017

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0


# HTTP Server
server:
  port: 16111