{{- if .Values.global.mongodb.sharding.enabled }}
apiVersion: v1
kind: Pod
metadata:
   name: setup-collection-sharding-hook
   annotations:
       "helm.sh/hook": "post-install"
spec:
  containers:
  - name: post-install-container
    image: python
    imagePullPolicy: Always
    command: ['sh', '-c', 'python -m pip install pymongo && python /tmp/init_social_network.py']  
    volumeMounts:
      - name: mongo-init-script
        mountPath: /tmp
  volumes:
  - name: mongo-init-script
    configMap:
      name: mongo-init-script
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
{{- end }}
