apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: train-ticket
build:
  platforms: ["linux/amd64"]
  local:
    concurrency: 16
    push: true
    useDockerCLI: false
  # tagPolicy:
  #   envTemplate:
  #     template: "{{.IMAGE_NAME}}:latest"
  artifacts:
    - image: ts-admin-basic-info-service
      context: ts-admin-basic-info-service
      docker:
        dockerfile: Dockerfile
    - image: ts-admin-order-service
      context: ts-admin-order-service
      docker:
        dockerfile: Dockerfile
    - image: ts-admin-route-service
      context: ts-admin-route-service
      docker:
        dockerfile: Dockerfile
    - image: ts-admin-travel-service
      context: ts-admin-travel-service
      docker:
        dockerfile: Dockerfile
    - image: ts-admin-user-service
      context: ts-admin-user-service
      docker:
        dockerfile: Dockerfile
    - image: ts-assurance-service
      context: ts-assurance-service
      docker:
        dockerfile: Dockerfile
    - image: ts-auth-service
      context: ts-auth-service
      docker:
        dockerfile: Dockerfile
    - image: ts-avatar-service
      context: ts-avatar-service
      docker:
        dockerfile: Dockerfile
    - image: ts-basic-service
      context: ts-basic-service
      docker:
        dockerfile: Dockerfile
    - image: ts-cancel-service
      context: ts-cancel-service
      docker:
        dockerfile: Dockerfile
    - image: ts-config-service
      context: ts-config-service
      docker:
        dockerfile: Dockerfile
    - image: ts-consign-price-service
      context: ts-consign-price-service
      docker:
        dockerfile: Dockerfile
    - image: ts-consign-service
      context: ts-consign-service
      docker:
        dockerfile: Dockerfile
    - image: ts-contacts-service
      context: ts-contacts-service
      docker:
        dockerfile: Dockerfile
    - image: ts-delivery-service
      context: ts-delivery-service
      docker:
        dockerfile: Dockerfile
    - image: ts-execute-service
      context: ts-execute-service
      docker:
        dockerfile: Dockerfile
    - image: ts-food-delivery-service
      context: ts-food-delivery-service
      docker:
        dockerfile: Dockerfile
    - image: ts-food-service
      context: ts-food-service
      docker:
        dockerfile: Dockerfile
    - image: ts-gateway-service
      context: ts-gateway-service
      docker:
        dockerfile: Dockerfile
    - image: ts-inside-payment-service
      context: ts-inside-payment-service
      docker:
        dockerfile: Dockerfile
    - image: ts-news-service
      context: ts-news-service
      docker:
        dockerfile: Dockerfile
    - image: ts-notification-service
      context: ts-notification-service
      docker:
        dockerfile: Dockerfile
    - image: ts-order-other-service
      context: ts-order-other-service
      docker:
        dockerfile: Dockerfile
    - image: ts-order-service
      context: ts-order-service
      docker:
        dockerfile: Dockerfile
    - image: ts-payment-service
      context: ts-payment-service
      docker:
        dockerfile: Dockerfile
    - image: ts-preserve-other-service
      context: ts-preserve-other-service
      docker:
        dockerfile: Dockerfile
    - image: ts-preserve-service
      context: ts-preserve-service
      docker:
        dockerfile: Dockerfile
    - image: ts-price-service
      context: ts-price-service
      docker:
        dockerfile: Dockerfile
    - image: ts-rebook-service
      context: ts-rebook-service
      docker:
        dockerfile: Dockerfile
    - image: ts-route-plan-service
      context: ts-route-plan-service
      docker:
        dockerfile: Dockerfile
    - image: ts-route-service
      context: ts-route-service
      docker:
        dockerfile: Dockerfile
    - image: ts-seat-service
      context: ts-seat-service
      docker:
        dockerfile: Dockerfile
    - image: ts-security-service
      context: ts-security-service
      docker:
        dockerfile: Dockerfile
    - image: ts-station-food-service
      context: ts-station-food-service
      docker:
        dockerfile: Dockerfile
    - image: ts-station-service
      context: ts-station-service
      docker:
        dockerfile: Dockerfile
    - image: ts-ticket-office-service
      context: ts-ticket-office-service
      docker:
        dockerfile: Dockerfile
    - image: ts-train-food-service
      context: ts-train-food-service
      docker:
        dockerfile: Dockerfile
    - image: ts-train-service
      context: ts-train-service
      docker:
        dockerfile: Dockerfile
    - image: ts-travel-plan-service
      context: ts-travel-plan-service
      docker:
        dockerfile: Dockerfile
    - image: ts-travel-service
      context: ts-travel-service
      docker:
        dockerfile: Dockerfile
    - image: ts-travel2-service
      context: ts-travel2-service
      docker:
        dockerfile: Dockerfile
    - image: ts-ui-dashboard
      context: ts-ui-dashboard
      docker:
        dockerfile: Dockerfile
    - image: ts-user-service
      context: ts-user-service
      docker:
        dockerfile: Dockerfile
    - image: ts-verification-code-service
      context: ts-verification-code-service
      docker:
        dockerfile: Dockerfile
    - image: ts-voucher-service
      context: ts-voucher-service
      docker:
        dockerfile: Dockerfile
    - image: ts-wait-order-service
      context: ts-wait-order-service
      docker:
        dockerfile: Dockerfile
