#spring:
#  data:
#    mongodb:
#      host: ts-preserve-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
##      database: piggymetrics
#      port: 27017

# HTTP Server
server:
  port: 14568  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-preserve-service
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: 5672

swagger:
  controllerPackage: preserve.controller
