# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Nightly Release

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  build_and_push_images:
    uses: ./.github/workflows/component-build-images.yml
    if: github.repository == 'open-telemetry/opentelemetry-demo'
    with:
      push: true
      version: nightly-${{ github.run_id }}
    secrets: inherit
