# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: "Build and Publish"

on:
  release:
    types: [published]

jobs:
  build_and_push_images:
    uses: ./.github/workflows/component-build-images.yml
    if: github.repository == 'open-telemetry/opentelemetry-demo'
    with:
      push: true
      version: ${{ github.event.release.tag_name }}
    secrets: inherit
