# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel2-service
  data:
    mongodb:
      host: ts-travel2-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0