# helm install redis-socialgraph bitnami/redis-cluster -n yanqizhang --set global.storageClass=local-storage --set persistence.size=20Gi --set global.redis.password=redissocialgraph --set cluster.nodes=6
# helm install redis-socialgraph bitnami/redis-cluster -n yanqizhang \
# --set global.storageClass=local-storage \
# --set persistence.size=20Gi \
# --set global.redis.password=redissocialgraph
# --set cluster.nodes=6
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: social-graph-store
  # namespace: yanqizhang
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisType
    value: cluster
  - name: redisHost
    value: redis-socialgraph-redis-cluster:6379
  - name: redisPassword
    value: redissocialgraph
  - name: keyPrefix
    value: none
