# helm install redis-socialgraph bitnami/redis -n yanqizhang --set global.storageClass=local-storage --set master.persistence.size=10Gi  --set replica.persistence.size=10Gi --set global.redis.password=redissocialgraph
# helm install redis-socialgraph bitnami/redis -n yanqizhang \
# --set global.storageClass=local-storage \
# --set master.persistence.size=10Gi \
# --set replica.persistence.size=10Gi \
# --set global.redis.password=redissocialgraph
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: social-graph-store
  namespace: yanqizhang
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-socialgraph-master:6379
  - name: redisPassword
    value: redissocialgraph
  - name: keyPrefix
    value: none
