apiVersion: v1
kind: Service
metadata:
  name: dapr-video-frontend-service
spec:
  type: NodePort
  selector:
    app: dapr-video-frontend
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 31985
      targetPort: 3500
      # targetPort: 5005
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31985