# helm install redis-img bitnami/redis-cluster -n yanqizhang --set global.storageClass=local-storage --set persistence.size=20Gi --set global.redis.password=redisstore --set cluster.nodes=6
# helm install redis-img bitnami/redis-cluster -n yanqizhang \
# --set global.storageClass=local-storage \
# --set persistence.size=20Gi \
# --set global.redis.password=redisstore
# --set cluster.nodes=6
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: image-store
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisType
    value: cluster
  - name: redisHost
    value: redis-img-redis-cluster:6379
  - name: redisPassword
    value: redisstore
  - name: keyPrefix
    value: none