{{- if .Values.global.memcached.cluster.enabled }}
apiVersion: v1
kind: Pod
metadata:
   name: setup-mcrouter-configmap
   annotations:
       "helm.sh/hook": "post-install"
spec:
  containers:
  - name: post-install-container
    image: bitnami/kubectl:latest
    imagePullPolicy: Always
    workingDir: /tmp
    command: ['bash', 'update_config_map.sh']  
    volumeMounts:
      - name: mcrouter-configmap
        mountPath: /tmp
      - name: scratch
        mountPath: scratch
  volumes:
  - name: mcrouter-configmap
    configMap:
      name: mcrouter-configmap
  - name: scratch
    emptyDir: {}
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
{{- end }}

