apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: consul
  name: consul
  namespace: hotel-res
spec:
  ports:
  - name: "8300"
    port: 8300
    targetPort: 8300
  - name: "8400"
    port: 8400
    targetPort: 8400
  - name: "8500"
    port: 8500
    targetPort: 8500
  - name: "8600"
    port: 8600
    protocol: UDP
    targetPort: 53
  selector:
    death-star-project: hotel-res
    app-name: consul
status:
  loadBalancer: {}
