apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: frontend
  namespace: hotel-res
  name: frontend
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    death-star-project: hotel-res
    app-name: frontend
status:
  loadBalancer: {}
