apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: geo
  namespace: hotel-res
  name: geo
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    death-star-project: hotel-res
    app-name: geo
status:
  loadBalancer: {}
