---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-out
  labels:
    death-star-project: hotel-res
    app-name: jaeger
  namespace: hotel-res
spec:
  type: NodePort
  ports:
  - port: 16686
  selector:
    death-star-project: hotel-res
    app-name: jaeger
---
apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: jaeger
  namespace: hotel-res
  name: jaeger
spec:
  ports:
  - name: "14269"
    port: 14269
    targetPort: 14269
  - name: "5778"
    port: 5778
    targetPort: 5778
  - name: "14268"
    port: 14268
    targetPort: 14268
  - name: "14267"
    port: 14267
    targetPort: 14267
  - name: "5775"
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: "6831"
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: "6832"
    port: 6832
    protocol: UDP
    targetPort: 6832
  selector:
    death-star-project: hotel-res
    app-name: jaeger
status:
  loadBalancer: {}
