apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    death-star-project: hotel-res
    app-name: jaeger
  namespace: hotel-res
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app-name: jaeger
  strategy: {}
  template:
    metadata:
      name: jaeger
      labels:
        death-star-project: hotel-res
        app-name: jaeger
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: jaegertracing/all-in-one:latest
        name: hotel-reserv-jaeger
        ports:
        - containerPort: 14269
        - containerPort: 5778
        - containerPort: 14268
        - containerPort: 14267
        - containerPort: 16686
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        resources: {}
      restartPolicy: Always
status: {}
