apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: memcached-reserve
  namespace: hotel-res
  name: memcached-reserve
spec:
  ports:
  - name: "11214"
    port: 11214
    targetPort: 11211
  selector:
    death-star-project: hotel-res
    app-name: memcached-reserve
status:
  loadBalancer: {}
