apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: memcached-rate
  namespace: hotel-res
  name: memcached-rate
spec:
  ports:
  - name: "11212"
    port: 11212
    targetPort: 11211
  selector:
    death-star-project: hotel-res
    app-name: memcached-rate
status:
  loadBalancer: {}
