apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: memcached-profile
  namespace: hotel-res
  name: memcached-profile
spec:
  ports:
  - name: "11213"
    port: 11213
    targetPort: 11211
  selector:
    death-star-project: hotel-res
    app-name: memcached-profile
status:
  loadBalancer: {}
