apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    death-star-project: hotel-res
    app-name: mongodb-recommendation
  namespace: hotel-res
  name: mongodb-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app-name: mongodb-recommendation
  strategy:
    type: Recreate
  template:
    metadata:
      name: mongodb-recommendation
      labels:
        death-star-project: hotel-res
        app-name: mongodb-recommendation
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: mongo:4.4.6
        name: hotel-reserv-recommendation-mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: recommendation
      hostname: recommendation-db
      restartPolicy: Always
      volumes:
      - name: recommendation
        persistentVolumeClaim:
          claimName: recommendation
status: {}
