apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    death-star-project: hotel-res
    app-name: mongodb-rate
  namespace: hotel-res
  name: mongodb-rate
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app-name: mongodb-rate
  strategy:
    type: Recreate
  template:
    metadata:
      name: mongodb-rate
      labels:
        death-star-project: hotel-res
        app-name: mongodb-rate
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: mongo:4.4.6
        name: hotel-reserv-rate-mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: rate
      hostname: rate-db
      restartPolicy: Always
      volumes:
      - name: rate
        persistentVolumeClaim:
          claimName: rate
status: {}
