apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: mongodb-geo
  namespace: hotel-res
  name: mongodb-geo
spec:
  ports:
  - name: "27018"
    port: 27018
    targetPort: 27017
  selector:
    death-star-project: hotel-res
    app-name: mongodb-geo
status:
  loadBalancer: {}
