apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: mongodb-rate
  namespace: hotel-res
  name: mongodb-rate
spec:
  ports:
  - name: "27020"
    port: 27020
    targetPort: 27017
  selector:
    death-star-project: hotel-res
    app-name: mongodb-rate
status:
  loadBalancer: {}
