apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: mongodb-profile
  namespace: hotel-res
  name: mongodb-profile
spec:
  ports:
  - name: "27019"
    port: 27019
    targetPort: 27017
  selector:
    death-star-project: hotel-res
    app-name: mongodb-profile
status:
  loadBalancer: {}
