apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    death-star-project: hotel-res
    app-name: mongodb-reservation
  namespace: hotel-res
  name: mongodb-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app-name: mongodb-reservation
  strategy:
    type: Recreate
  template:
    metadata:
      name: mongodb-reservation
      labels:
        death-star-project: hotel-res
        app-name: mongodb-reservation
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: mongo:4.4.6
        name: hotel-reserv-reservation-mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: reservation
      hostname: reservation-db
      restartPolicy: Always
      volumes:
      - name: reservation
        persistentVolumeClaim:
          claimName: reservation
status: {}
