apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: mongodb-recommendation
  namespace: hotel-res
  name: mongodb-recommendation
spec:
  ports:
  - name: "27021"
    port: 27021
    targetPort: 27017
  selector:
    death-star-project: hotel-res
    app-name: mongodb-recommendation
status:
  loadBalancer: {}
