apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: mongodb-user
  namespace: hotel-res
  name: mongodb-user
spec:
  ports:
  - name: "27023"
    port: 27023
    targetPort: 27017
  selector:
    death-star-project: hotel-res
    app-name: mongodb-user
status:
  loadBalancer: {}
