apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    death-star-project: hotel-res
    app-name: mongodb-profile
  namespace: hotel-res
  name: mongodb-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app-name: mongodb-profile
  strategy:
    type: Recreate
  template:
    metadata:
      name: mongodb-profile
      labels:
        death-star-project: hotel-res
        app-name: mongodb-profile
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: mongo:4.4.6
        name: hotel-reserv-profile-mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: profile
      hostname: profile-db
      restartPolicy: Always
      volumes:
      - name: profile
        persistentVolumeClaim:
          claimName: profile
status: {}
