apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: mongodb-reservation
  namespace: hotel-res
  name: mongodb-reservation
spec:
  ports:
  - name: "27022"
    port: 27022
    targetPort: 27017
  selector:
    death-star-project: hotel-res
    app-name: mongodb-reservation
status:
  loadBalancer: {}
