apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: profile
  namespace: hotel-res
  name: profile
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    death-star-project: hotel-res
    app-name: profile
status:
  loadBalancer: {}
