apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: rate
  namespace: hotel-res
  name: rate
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8084
  selector:
    death-star-project: hotel-res
    app-name: rate
status:
  loadBalancer: {}
