apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    death-star-project: hotel-res
    app-name: recommendation
  namespace: hotel-res
  name: recommendation
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
