apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: recommendation
  namespace: hotel-res
  name: recommendation
spec:
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8085
  selector:
    death-star-project: hotel-res
    app-name: recommendation
status:
  loadBalancer: {}
