apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: reservation
  namespace: hotel-res
  name: reservation
spec:
  ports:
  - name: "8087"
    port: 8087
    targetPort: 8087
  selector:
    death-star-project: hotel-res
    app-name: reservation
status:
  loadBalancer: {}
