apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: search
  namespace: hotel-res
  name: search
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    death-star-project: hotel-res
    app-name: search
status:
  loadBalancer: {}
