apiVersion: v1
kind: Service
metadata:
  labels:
    death-star-project: hotel-res
    app-name: user
  namespace: hotel-res
  name: user
spec:
  ports:
  - name: "8086"
    port: 8086
    targetPort: 8086
  selector:
    death-star-project: hotel-res
    app-name: user
status:
  loadBalancer: {}
