version: '3'
services:


  rabbitmq:
    image: 10.141.212.25:5555/cluster-ts-rabbitmq-management
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  # kafka:
  #   container_name: kafka
  #   image: spotify/kafka:latest
  #   ports:
  #    - 2181:2181
  #    - 9092:9092
  #   networks:
  #     - my-network


  zipkin:
    image: 10.141.212.25:5555/cluster-ts-openzipkin-zipkin
    ports:
      - 9411:9411
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  redis:
    image: 10.141.212.25:5555/cluster-ts-redis
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network
  

  ts-ui-dashboard:
    build: ts-ui-dashboard
    # image: 10.141.212.25:5555/cluster-ts-ui-dashboard
    image: 10.141.212.25:5555/cluster-ts-ui-dashboard
    restart: always
    ports:
      - 80:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-login-service:
    build: ts-login-service
    # image: 10.141.212.25:5555/cluster-ts-login-service
    image: 10.141.212.25:5555/cluster-ts-login-service
    restart: always
    ports:
      - 12342:12342
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-account-mongo:
    image: 10.141.212.25:5555/cluster-ts-mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-route-service:
      build: ts-route-service
      image: 10.141.212.25:5555/cluster-ts-route-service
      restart: always
      ports:
           - 11178:11178
      networks:
        - my-network

  ts-route-mongo:
    image: 10.141.212.25:5555/cluster-ts-mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
        - my-network

  ts-register-service:
    build: ts-register-service
    # image: 10.141.212.25:5555/cluster-ts-register-service
    image: 10.141.212.25:5555/cluster-ts-register-service
    restart: always
    ports:
      - 12344:12344
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network


  ts-sso-service:
    build: ts-sso-service
    image: 10.141.212.25:5555/cluster-ts-sso-service
    restart: always
    ports:
      - 12349:12349
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network



  ts-verification-code-service:
    build: ts-verification-code-service
    image: 10.141.212.25:5555/cluster-ts-verification-code-service
    restart: always
    ports:
      - 15678:15678
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-contacts-service:
    build: ts-contacts-service
    image: 10.141.212.25:5555/cluster-ts-contacts-service
    restart: always
    ports:
      - 12347:12347
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-contacts-mongo:
      image: 10.141.212.25:5555/cluster-ts-mongo
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - my-network

  ts-order-service:
    build: ts-order-service
    image: 10.141.212.25:5555/cluster-ts-order-service
    restart: always
    ports:
      - 12031:12031
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-order-mongo:
    image: 10.141.212.25:5555/cluster-ts-mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network


  ts-order-other-service:
    build: ts-order-other-service
    image: 10.141.212.25:5555/cluster-ts-order-other-service
    restart: always
    ports:
      - 12032:12032
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-order-other-mongo:
    image: 10.141.212.25:5555/cluster-ts-mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network


  ts-config-service:
    build: ts-config-service
    image: 10.141.212.25:5555/cluster-ts-config-service
    restart: always
    ports:
      - 15679:15679
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-config-mongo:
    image: 10.141.212.25:5555/cluster-ts-mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-station-service:
    build: ts-station-service
    image: 10.141.212.25:5555/cluster-ts-station-service
    restart: always
    ports:
      - 12345:12345
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-station-mongo:
    image: 10.141.212.25:5555/cluster-ts-mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-train-service:
    build: ts-train-service
    image: 10.141.212.25:5555/cluster-ts-train-service
    restart: always
    ports:
      - 14567:14567
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-train-mongo:
    image: 10.141.212.25:5555/cluster-ts-mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-travel-service:
    build: ts-travel-service
    image: 10.141.212.25:5555/cluster-ts-travel-service
    restart: always
    ports:
      - 12346:12346
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-travel-mongo:
    image: 10.141.212.25:5555/cluster-ts-mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-travel2-service:
      build: ts-travel2-service
      image: 10.141.212.25:5555/cluster-ts-travel2-service
      restart: always
      ports:
        - 16346:16346
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - my-network

  ts-travel2-mongo:
      image: 10.141.212.25:5555/cluster-ts-mongo
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - my-network

  ts-preserve-service:
    build: ts-preserve-service
    image: 10.141.212.25:5555/cluster-ts-preserve-service
    restart: always
    ports:
      - 14568:14568
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  ts-preserve-other-service:
    build: ts-preserve-other-service
    image: 10.141.212.25:5555/cluster-ts-preserve-other-service
    restart: always
    ports:
      - 14569:14569
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network


  ts-basic-service:
      build: ts-basic-service
      image: 10.141.212.25:5555/cluster-ts-basic-service
      restart: always
      ports:
        - 15680:15680
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
          - my-network

  ts-ticketinfo-service:
        build: ts-ticketinfo-service
        image: 10.141.212.25:5555/cluster-ts-ticketinfo-service
        restart: always
        ports:
          - 15681:15681
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-price-service:
        build: ts-price-service
        image: 10.141.212.25:5555/cluster-ts-price-service
        restart: always
        ports:
          - 16579:16579
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-price-mongo:
        image: 10.141.212.25:5555/cluster-ts-mongo
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-notification-service:
        build: ts-notification-service
        image: 10.141.212.25:5555/cluster-ts-notification-service
        restart: always
        ports:
          - 17853:17853
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-security-service:
        build: ts-security-service
        image: 10.141.212.25:5555/cluster-ts-security-service
        restart: always
        ports:
          - 11188:11188
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-security-mongo:
        image: 10.141.212.25:5555/cluster-ts-mongo
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-inside-payment-service:
        build: ts-inside-payment-service
        image: 10.141.212.25:5555/cluster-ts-inside-payment-service
        restart: always
        ports:
          - 18673:18673
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-inside-payment-mongo:
        image: 10.141.212.25:5555/cluster-ts-mongo
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-execute-service:
        build: ts-execute-service
        image: 10.141.212.25:5555/cluster-ts-execute-service
        restart: always
        ports:
          - 12386:12386
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-payment-service:
        build: ts-payment-service
        image: 10.141.212.25:5555/cluster-ts-payment-service
        restart: always
        ports:
          - 19001:19001
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-payment-mongo:
        image: 10.141.212.25:5555/cluster-ts-mongo
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-rebook-service:
        build: ts-rebook-service
        image: 10.141.212.25:5555/cluster-ts-rebook-service
        restart: always
        ports:
          - 18886:18886
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-rebook-mongo:
        image: 10.141.212.25:5555/cluster-ts-mongo
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-cancel-service:
        build: ts-cancel-service
        image: 10.141.212.25:5555/cluster-ts-cancel-service
        restart: always
        ports:
          - 18885:18885
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-assurance-service:
          build: ts-assurance-service
          image: 10.141.212.25:5555/cluster-ts-assurance-service
          restart: always
          ports:
            - 18888:18888
          deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
          networks:
            - my-network

  ts-assurance-mongo:
        image: 10.141.212.25:5555/cluster-ts-mongo
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-seat-service:
        build: ts-seat-service
        image: 10.141.212.25:5555/cluster-ts-seat-service
        restart: always
        ports:
          - 18898:18898
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-travel-plan-service:
        build: ts-travel-plan-service
        image: 10.141.212.25:5555/cluster-ts-travel-plan-service
        restart: always
        ports:
          - 14322:14322
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-ticket-office-service:
        build: ts-ticket-office-service
        image: 10.141.212.25:5555/cluster-ts-ticket-office-service
        restart: always
        ports:
          - 16108:16108
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-ticket-office-mongo:
        image: 10.141.212.25:5555/cluster-ts-mongo
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-news-service:
        build: ts-news-service
        image: 10.141.212.25:5555/cluster-ts-news-service
        restart: always
        ports:
          - 12862:12862
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-news-mongo:
        image: 10.141.212.25:5555/cluster-ts-mongo
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-voucher-mysql:
         image: 10.141.212.25:5555/cluster-ts-mysql
         expose:
            - "3306"
         environment:
            MYSQL_ROOT_PASSWORD: root
         deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
         networks:
           - my-network

  ts-voucher-service:
          build: ts-voucher-service
          image: 10.141.212.25:5555/cluster-ts-voucher-service
          restart: always
          ports:
            - 16101:16101
          depends_on:
            - ts-voucher-mysql
          deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
          volumes:
            - /var/lib/mysql
          networks:
            - my-network

  ts-food-map-service:
        build: ts-food-map-service
        image: 10.141.212.25:5555/cluster-ts-food-map-service
        restart: always
        ports:
          - 18855:18855
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-food-map-mongo:
          image: 10.141.212.25:5555/cluster-ts-mongo
          deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
          networks:
            - my-network

  ts-route-plan-service:
          build: ts-route-plan-service
          image: 10.141.212.25:5555/cluster-ts-route-plan-service
          restart: always
          ports:
            - 14578:14578
          deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
          networks:
            - my-network

  ts-food-service:
      build: ts-food-service
      image: 10.141.212.25:5555/cluster-ts-food-service
      restart: always
      ports:
        - 18856:18856
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - my-network

  ts-consign-service:
      build: ts-consign-service
      image: 10.141.212.25:5555/cluster-ts-consign-service
      restart: always
      ports:
        - 16111:16111
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - my-network

  ts-consign-mongo:
      image: 10.141.212.25:5555/cluster-ts-mongo
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - my-network

  ts-consign-price-service:
            build: ts-consign-price-service
            image: 10.141.212.25:5555/cluster-ts-consign-price-service
            restart: always
            ports:
              - 16110:16110
            deploy:
              replicas: 1
              restart_policy:
                condition: on-failure
            networks:
              - my-network

  ts-consign-price-mongo:
            image: 10.141.212.25:5555/cluster-ts-mongo
            deploy:
              replicas: 1
              restart_policy:
                condition: on-failure
            networks:
              - my-network

  ts-food-mongo:
            image: 10.141.212.25:5555/cluster-ts-mongo
            deploy:
              replicas: 1
              restart_policy:
                condition: on-failure
            networks:
              - my-network

  ts-admin-basic-info-service:
        build: ts-admin-basic-info-service
        image: 10.141.212.25:5555/cluster-ts-admin-basic-info-service
        restart: always
        ports:
          - 18767:18767
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  ts-admin-order-service:
            build: ts-admin-order-service
            image: 10.141.212.25:5555/cluster-ts-admin-order-service
            restart: always
            ports:
              - 16112:16112
            deploy:
              replicas: 1
              restart_policy:
                condition: on-failure
            networks:
              - my-network

  ts-admin-route-service:
              build: ts-admin-route-service
              image: 10.141.212.25:5555/cluster-ts-admin-route-service
              restart: always
              ports:
                - 16113:16113
              deploy:
                replicas: 1
                restart_policy:
                  condition: on-failure
              networks:
                - my-network

  ts-admin-travel-service:
                build: ts-admin-travel-service
                image: 10.141.212.25:5555/cluster-ts-admin-travel-service
                restart: always
                ports:
                  - 16114:16114
                deploy:
                  replicas: 1
                  restart_policy:
                    condition: on-failure
                networks:
                  - my-network

  ts-admin-user-service:
                  build: ts-admin-user-service
                  image: 10.141.212.25:5555/cluster-ts-admin-user-service
                  restart: always
                  ports:
                    - 16115:16115
                  deploy:
                    replicas: 1
                    restart_policy:
                      condition: on-failure
                  networks:
                    - my-network

networks:
  my-network:
    driver: overlay
    # driver: bridge





