apiVersion: v1
kind: Service
metadata:
  name: ts-admin-basic-info-service
spec:
  ports:
    - port: 18767
  selector:
   app: ts-admin-basic-info-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-order-service
spec:
  ports:
    - port: 16112
  selector:
   app: ts-admin-order-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-route-service
spec:
  ports:
    - port: 16113
  selector:
   app: ts-admin-route-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-travel-service
spec:
  ports:
    - port: 16114
  selector:
   app: ts-admin-travel-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-user-service
spec:
  ports:
    - port: 16115
  selector:
   app: ts-admin-user-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-assurance-service
spec:
  ports:
    - port: 18888
  selector:
   app: ts-assurance-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-basic-service
spec:
  ports:
    - port: 15680
  selector:
   app: ts-basic-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-cancel-service
spec:
  ports:
    - port: 18885
  selector:
   app: ts-cancel-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-config-service
spec:
  ports:
    - port: 15679
  selector:
   app: ts-config-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-consign-price-service
spec:
  ports:
    - port: 16110
  selector:
   app: ts-consign-price-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-consign-service
spec:
  ports:
    - port: 16111
  selector:
   app: ts-consign-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-contacts-service
spec:
  ports:
    - port: 12347
  selector:
   app: ts-contacts-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-execute-service
spec:
  ports:
    - port: 12386
  selector:
   app: ts-execute-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-food-map-service
spec:
  ports:
    - port: 18855
  selector:
   app: ts-food-map-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-food-service
spec:
  ports:
    - port: 18856
  selector:
   app: ts-food-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-service
spec:
  ports:
    - port: 18673
  selector:
   app: ts-inside-payment-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-login-service
spec:
  ports:
    - port: 12342
  selector:
   app: ts-login-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-notification-service
spec:
  ports:
    - port: 17853
  selector:
   app: ts-notification-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-news-service
spec:
  ports:
    - port: 12862
  selector:
   app: ts-news-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-service
spec:
  ports:
    - port: 12032
  selector:
   app: ts-order-other-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-service
spec:
  ports:
    - port: 12031
  selector:
   app: ts-order-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-payment-service
spec:
  ports:
    - port: 19001
  selector:
   app: ts-payment-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-other-service
spec:
  ports:
    - port: 14569
  selector:
   app: ts-preserve-other-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-service
spec:
  ports:
    - port: 14568
  selector:
   app: ts-preserve-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-price-service
spec:
  ports:
    - port: 16579
  selector:
   app: ts-price-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-rebook-service
spec:
  ports:
    - port: 18886
  selector:
   app: ts-rebook-service