apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-socialnet-frontend
  labels:
    app: dapr-socialnet-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dapr-socialnet-frontend
  template:
    metadata:
      labels:
        app: dapr-socialnet-frontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-socialnet-frontend"
        dapr.io/app-port: "5005"
        dapr.io/app-protocol: "grpc"
        dapr.io/sidecar-listen-addresses: "0.0.0.0"
        dapr.io/http-max-request-size: "16"
        dapr.io/sidecar-image: "daprio/daprd:1.8.3"
        # dapr.io/config: "tracing"
        # dapr.io/log-level: "debug"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8084"
    spec:
      containers:
      - name: dapr-socialnet-frontend
        image: sailresearch/dapr-socialnet-frontend:latest
        imagePullPolicy: Always
        # ports:
        # - containerPort: 5005
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "30"
        env:
        - name: PORT
          value: "5005"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: ADDRESS
          value: ":5005"
        - name: PROM_ADDRESS
          value: ":8084"
        - name: IMAGE_STORE
          value: "image-store"
        # object-detect
        - name: OBJECT_DETECT_PUBSUB
          value: "object-detect-pubsub"
        - name: OBJECT_DETECT_TOPIC
          value: "object-detect"
        # sentiment
        - name: SENTIMENT_PUBSUB
          value: sentiment-pubsub
        - name: SENTIMENT_TOPIC
          value: sentiment
        # timeline-update
        - name: TIMELINE_PUBSUB
          value: timeline-events
        - name: TIMELINE_TOPIC
          value: timeline
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: cpu
      #           operator: NotIn
      #           values:
      #           - beefy
          