#spring:
#  data:
#    mongodb:
#      host: ts-preserve-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
##      database: piggymetrics
#      port: 27017

# HTTP Server
server:
  port: 8080  # HTTP (Tomcat) port

spring:
  application:
    name: ts-preserve-service
  rabbitmq:
    host: ${RABBITMQ_HOST:ts-rabbitmq}
    port: 5672

swagger:
  controllerPackage: preserve.controller
