#spring:
#  data:
#    mongodb:
#      host: ts-preserve-other-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
##      database: piggymetrics
#      port: 27017

# HTTP Server
server:
  port: 8080 # HTTP (Tomcat) port

spring:
  application:
    name: ts-preserve-other-service
  rabbitmq:
    host: ${RABBITMQ_HOST:ts-rabbitmq}
    port: 5672

swagger:
  controllerPackage: preserveOther.controller
