# helm install redis-timeline bitnami/redis-cluster -n yanqizhang --set global.storageClass=local-storage --set persistence.size=20Gi --set global.redis.password=redistimeline --set cluster.nodes=6
# helm install redis-timeline bitnami/redis-cluster -n yanqizhang \
# --set global.storageClass=local-storage \
# --set persistence.size=20Gi \
# --set global.redis.password=redistimeline
# --set cluster.nodes=6
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: timeline-store
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisType
    value: cluster
  - name: redisHost
    value: redis-timeline-redis-cluster:6379
  - name: redisPassword
    value: redistimeline
  - name: keyPrefix
    value: none
