# HTTP Server
server:
  port: 18888  # HTTP (Tomcat) port

spring:
  main:
    web-application-type: reactive
  application:
    name: ts-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
    gateway:
      routes:
        - id: admin-basic-info
          uri: lb://${ADMIN_BASIC_INFO_SERVICE_HOST:ts-admin-basic-info-service}
          predicates:
            - Path=/api/v1/adminbasicservice/**

        - id: admin-order
          uri: lb://${ADMIN_ORDER_SERVICE_HOST:ts-admin-order-service}
          predicates:
            - Path=/api/v1/adminorderservice/**

        - id: admin-route
          uri: lb://${ADMIN_ROUTE_SERVICE_HOST:ts-admin-route-service}
          predicates:
            - Path=/api/v1/adminrouteservice/**

        - id: admin-travel
          uri: lb://${ADMIN_TRAVEL_SERVICE_HOST:ts-admin-travel-service}
          predicates:
            - Path=/api/v1/admintravelservice/**

        - id: admin-user
          uri: lb://${ADMIN_USER_SERVICE_HOST:ts-admin-user-service}
          predicates:
            - Path=/api/v1/adminuserservice/users/**

        - id: assurance
          uri: lb://${ASSURANCE_SERVICE_HOST:ts-assurance-service}
          predicates:
            - Path=/api/v1/assuranceservice/**

        - id: auth
          uri: lb://${AUTH_SERVICE_HOST:ts-auth-service}
          predicates:
            - Path=/api/v1/auth/**

        - id: auth-user
          uri: lb://${AUTH_SERVICE_HOST:ts-auth-service}
          predicates:
            - Path=/api/v1/users/**

        - id: avatar
          uri: lb://${AVATAR_SERVICE_HOST:ts-avatar-service}
          predicates:
            - Path=/api/v1/avatar/**

        - id: basic
          uri: lb://${BASIC_SERVICE_HOST:ts-basic-service}
          predicates:
            - Path=/api/v1/basicservice/**

        - id: cancel
          uri: lb://${CANCEL_SERVICE_HOST:ts-cancel-service}
          predicates:
            - Path=/api/v1/cancelservice/**

        - id: config
          uri: lb://${CONFIG_SERVICE_HOST:ts-config-service}
          predicates:
            - Path=/api/v1/configservice/**

        - id: consign-price
          uri: lb://${CONSIGN_PRICE_SERVICE_HOST:ts-consign-price-service}
          predicates:
            - Path=/api/v1/consignpriceservice/**

        - id: consign
          uri: lb://${CONSIGN_SERVICE_HOST:ts-consign-service}
          predicates:
            - Path=/api/v1/consignservice/**

        - id: contacts
          uri: lb://${CONTACTS_SERVICE_HOST:ts-contacts-service}
          predicates:
            - Path=/api/v1/contactservice/**

        - id: execute
          uri: lb://${EXECUTE_SERVICE_HOST:ts-execute-service}
          predicates:
            - Path=/api/v1/executeservice/**

        - id: food
          uri: lb://${FOOD_SERVICE_HOST:ts-food-service}
          predicates:
            - Path=/api/v1/foodservice/**

        - id: inside-payment
          uri: lb://${INSIDE_PAYMENT_SERVICE_HOST:ts-inside-payment-service}
          predicates:
            - Path=/api/v1/inside_pay_service/**

        - id: notification
          uri: lb://${NOTIFICATION_SERVICE_HOST:ts-notification-service}
          predicates:
            - Path=/api/v1/notifyservice/**

        - id: order-other
          uri: lb://${ORDER_OTHER_SERVICE_HOST:ts-order-other-service}
          predicates:
            - Path=/api/v1/orderOtherService/**

        - id: order
          uri: lb://${ORDER_SERVICE_HOST:ts-order-service}
          predicates:
            - Path=/api/v1/orderservice/**

        - id: payment
          uri: lb://${PAYMENT_SERVICE_HOST:ts-payment-service}
          predicates:
            - Path=/api/v1/paymentservice/**

        - id: preserve-other
          uri: lb://${PRESERVE_OTHER_SERVICE_HOST:ts-preserve-other-service}
          predicates:
            - Path=/api/v1/preserveotherservice/**

        - id: preserve
          uri: lb://${PRESERVE_SERVICE_HOST:ts-preserve-service}
          predicates:
            - Path=/api/v1/preserveservice/**

        - id: price
          uri: lb://${PRICE_SERVICE_HOST:ts-price-service}
          predicates:
            - Path=/api/v1/priceservice/**

        - id: rebook
          uri: lb://${REBOOK_SERVICE_HOST:ts-rebook-service}
          predicates:
            - Path=/api/v1/rebookservice/**

        - id: route-plan
          uri: lb://${ROUTE_PLAN_SERVICE_HOST:ts-route-plan-service}
          predicates:
            - Path=/api/v1/routeplanservice/**

        - id: route
          uri: lb://${ROUTE_SERVICE_HOST:ts-route-service}
          predicates:
            - Path=/api/v1/routeservice/**

        - id: seat
          uri: lb://${SEAT_SERVICE_HOST:ts-seat-service}
          predicates:
            - Path=/api/v1/seatservice/**

        - id: security
          uri: lb://${SECURITY_SERVICE_HOST:ts-security-service}
          predicates:
            - Path=/api/v1/securityservice/**

        - id: station-food
          uri: lb://${STATION_FOOD_SERVICE_HOST:ts-station-food-service}
          predicates:
            - Path=/api/v1/stationfoodservice/**

        - id: station
          uri: lb://${STATION_SERVICE_HOST:ts-station-service}
          predicates:
            - Path=/api/v1/stationservice/**

        - id: train-food
          uri: lb://${TRAIN_FOOD_SERVICE_HOST:ts-train-food-service}
          predicates:
            - Path=/api/v1/trainfoodservice/**

        - id: train
          uri: lb://${TRAIN_SERVICE_HOST:ts-train-service}
          predicates:
            - Path=/api/v1/trainservice/**

        - id: travel2
          uri: lb://${TRAVEL2_SERVICE_HOST:ts-travel2-service}
          predicates:
            - Path=/api/v1/travel2service/**

        - id: travel-plan
          uri: lb://${TRAVEL_PLAN_SERVICE_HOST:ts-travel-plan-service}
          predicates:
            - Path=/api/v1/travelplanservice/**

        - id: travel
          uri: lb://${TRAVEL_SERVICE_HOST:ts-travel-service}
          predicates:
            - Path=/api/v1/travelservice/**

        - id: user
          uri: lb://${USER_SERVICE_HOST:ts-user-service}
          predicates:
            - Path=/api/v1/userservice/users/**

        - id: verification-code
          uri: lb://${VERIFICATION_CODE_SERVICE_HOST:ts-verification-code-service}
          predicates:
            - Path=/api/v1/verifycode/**
