apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-recommend
  labels:
    app: dapr-recommend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dapr-recommend
  template:
    metadata:
      labels:
        app: dapr-recommend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-recommend"
        dapr.io/app-port: "5005"
        dapr.io/app-protocol: "grpc"
        dapr.io/sidecar-listen-addresses: "0.0.0.0"
        dapr.io/sidecar-image: "daprio/daprd:1.8.3"
        # dapr.io/config: "tracing"
        # dapr.io/log-level: "debug"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8084"
    spec:
      containers:
      - name: dapr-recommend
        image: sailresearch/dapr-recommend:latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "30"
        # ports:
        # - containerPort: 5005
        env:
        - name: PORT
          value: "5005"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: ADDRESS
          value: ":5005"
        - name: PROM_ADDRESS
          value: ":8084"
        - name: MAX_REF
          value: "10"
        - name: MAX_RECMD_SORT
          value: "10"
        - name: MAX_RECMD_RAND
          value: "10"
      # affinity:
      #     nodeAffinity:
      #       requiredDuringSchedulingIgnoredDuringExecution:
      #         nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: cpu
      #             operator: NotIn
      #             values:
      #             - beefy