apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-dates
  labels:
    app: dapr-dates
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dapr-dates
  template:
    metadata:
      labels:
        app: dapr-dates
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-dates"
        dapr.io/app-port: "5005"
        dapr.io/app-protocol: "grpc"
        dapr.io/sidecar-listen-addresses: "0.0.0.0"
        dapr.io/sidecar-image: "daprio/daprd:1.8.3"
        # dapr.io/config: "tracing"
        # dapr.io/log-level: "debug"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8084"
    spec:
      containers:
      - name: dapr-dates
        image: sailresearch/dapr-dates:latest
        imagePullPolicy: Always
        # ports:
        # - containerPort: 5005
        env:
        - name: PORT
          value: "5005"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: ADDRESS
          value: ":5005"
        - name: PROM_ADDRESS
          value: ":8084"
        - name: DATE_STORE
          value: date-store