spring:
  application:
    name: ts-route-plan-service

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0

# HTTP Server
server:
  port: 14578 # HTTP (Tomcat) port