version: '3'
services:

#  rabbitmq:
#    image: rabbitmq:management
#    ports:
#      - 5672:5672
#      - 15672:15672
#    networks:
#      - my-network

  # kafka:
  #   container_name: kafka
  #   image: spotify/kafka:latest
  #   ports:
  #    - 2181:2181
  #    - 9092:9092
  #   networks:
  #     - my-network

#  zipkin:
#    image: openzipkin/zipkin
#    ports:
#      - 9411:9411
#    networks:
#      - my-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # nginx
  ts-ui-dashboard:
    image: codewisdom/ts-ui-dashboard-with-jaeger:v1
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          

  # java, default Xmx200m
  ts-auth-service:
    image: codewisdom/ts-auth-service-with-jaeger:v1
    restart: always
    ports:
      - 12340:12340
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-auth-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-user-service:
    image: codewisdom/ts-user-service-with-jaeger:v1
    restart: always
    ports:
      - 12342:12342
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-user-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-verification-code-service:
    image: codewisdom/ts-verification-code-service-with-jaeger:v1
    restart: always
    ports:
      - 15678:15678
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-account-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-route-service:
    image: codewisdom/ts-route-service-with-jaeger:v1
    restart: always
    ports:
         - 11178:11178
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-route-mongo:
    image: mongo
    networks:
        - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-contacts-service:
    image: codewisdom/ts-contacts-service-with-jaeger:v1
    restart: always
    ports:
      - 12347:12347
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-contacts-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-order-service:
    image: codewisdom/ts-order-service-with-jaeger:v1
    restart: always
    ports:
      - 12031:12031
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-order-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-order-other-service:
    image: codewisdom/ts-order-other-service-with-jaeger:v1
    restart: always
    ports:
      - 12032:12032
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-order-other-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-config-service:
    image: codewisdom/ts-config-service-with-jaeger:v1
    restart: always
    ports:
      - 15679:15679
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-config-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-station-service:
    image: codewisdom/ts-station-service-with-jaeger:v1
    restart: always
    ports:
      - 12345:12345
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-station-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-train-service:
    image: codewisdom/ts-train-service-with-jaeger:v1
    restart: always
    ports:
      - 14567:14567
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-train-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-travel-service:
    image: codewisdom/ts-travel-service-with-jaeger:v1
    restart: always
    ports:
      - 12346:12346
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-travel-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-travel2-service:
    image: codewisdom/ts-travel2-service-with-jaeger:v1
    restart: always
    ports:
      - 16346:16346
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-travel2-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-preserve-service:
    image: codewisdom/ts-preserve-service-with-jaeger:v1
    restart: always
    ports:
      - 14568:14568
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-preserve-other-service:
    image: codewisdom/ts-preserve-other-service-with-jaeger:v1
    restart: always
    ports:
      - 14569:14569
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-basic-service:
    image: codewisdom/ts-basic-service-with-jaeger:v1
    restart: always
    ports:
      - 15680:15680
    networks:
        - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-ticketinfo-service:
    image: codewisdom/ts-ticketinfo-service-with-jaeger:v1
    restart: always
    ports:
      - 15681:15681
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-price-service:
    image: codewisdom/ts-price-service-with-jaeger:v1
    restart: always
    ports:
      - 16579:16579
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-price-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-notification-service:
    image: codewisdom/ts-notification-service-with-jaeger:v1
    restart: always
    ports:
      - 17853:17853
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-security-service:
    image: codewisdom/ts-security-service-with-jaeger:v1
    restart: always
    ports:
      - 11188:11188
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-security-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-inside-payment-service:
    image: codewisdom/ts-inside-payment-service-with-jaeger:v1
    restart: always
    ports:
      - 18673:18673
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-inside-payment-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-execute-service:
    image: codewisdom/ts-execute-service-with-jaeger:v1
    restart: always
    ports:
      - 12386:12386
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-payment-service:
    image: codewisdom/ts-payment-service-with-jaeger:v1
    restart: always
    ports:
      - 19001:19001
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-payment-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-rebook-service:
    image: codewisdom/ts-rebook-service-with-jaeger:v1
    restart: always
    ports:
      - 18886:18886
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-rebook-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-cancel-service:
    image: codewisdom/ts-cancel-service-with-jaeger:v1
    restart: always
    ports:
      - 18885:18885
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-assurance-service:
    image: codewisdom/ts-assurance-service-with-jaeger:v1
    restart: always
    ports:
      - 18888:18888
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-assurance-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-seat-service:
    image: codewisdom/ts-seat-service-with-jaeger:v1
    restart: always
    ports:
      - 18898:18898
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-travel-plan-service:
    image: codewisdom/ts-travel-plan-service-with-jaeger:v1
    restart: always
    ports:
      - 14322:14322
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # Written in JavaScript
  ts-ticket-office-service:
    image: codewisdom/ts-ticket-office-service-with-jaeger:v1
    restart: always
    ports:
      - 16108:16108
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          

  ts-ticket-office-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # Written in GO
  ts-news-service:
    image: codewisdom/ts-news-service-with-jaeger:v1
    restart: always
    ports:
      - 12862:12862
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-news-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  ts-voucher-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # Written in Python
  ts-voucher-service:
    image: codewisdom/ts-voucher-service-with-jaeger:v1
    restart: always
    ports:
      - 16101:16101
    depends_on:
      - ts-voucher-mysql
    volumes:
      - /var/lib/mysql
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-food-map-service:
    image: codewisdom/ts-food-map-service-with-jaeger:v1
    restart: always
    ports:
      - 18855:18855
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-food-map-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-route-plan-service:
    image: codewisdom/ts-route-plan-service-with-jaeger:v1
    restart: always
    ports:
      - 14578:14578
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-food-service:
    image: codewisdom/ts-food-service-with-jaeger:v1
    restart: always
    ports:
      - 18856:18856
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  # java, default Xmx200m
  ts-consign-service:
    image: codewisdom/ts-consign-service-with-jaeger:v1
    restart: always
    ports:
      - 16111:16111
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-consign-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # java, default Xmx200m
  ts-consign-price-service:
    image: codewisdom/ts-consign-price-service-with-jaeger:v1
    restart: always
    ports:
      - 16110:16110
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-consign-price-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  ts-food-mongo:
    image: mongo
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

  # ADMIN SERVICES ------------------------------------------------
  ts-admin-basic-info-service:
    image: codewisdom/ts-admin-basic-info-service-with-jaeger:v1
    restart: always
    ports:
      - 18767:18767
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-admin-order-service:
    image: codewisdom/ts-admin-order-service-with-jaeger:v1
    restart: always
    ports:
      - 16112:16112
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          

  ts-admin-route-service:
    image: codewisdom/ts-admin-route-service-with-jaeger:v1
    restart: always
    ports:
      - 16113:16113
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-admin-travel-service:
    image: codewisdom/ts-admin-travel-service-with-jaeger:v1
    restart: always
    ports:
      - 16114:16114
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  ts-admin-user-service:
    image: codewisdom/ts-admin-user-service-with-jaeger:v1
    restart: always
    ports:
      - 16115:16115
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
          
  jaeger:
    image: jaegertracing/all-in-one:1.15
    ports:
      - 16686:16686
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - my-network
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}

networks:
    my-network:
      driver: overlay
      # driver: bridge

