version: '3.7'

services:
  server:
    image: flaviostutz/json-server
    ports:
      - "80:3000"
    environment:
      - COLLECTIONS=cars,houses
    deploy:
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE_NAME}
      restart_policy:
        condition: any

  