{{- if .Values.global.redis.cluster.enabled }}
apiVersion: v1
kind: Pod
metadata:
   name: redis-cluster-readiness-hook
   annotations:
       "helm.sh/hook": "post-install"
spec:
  containers:
  - name: post-install-container
    image: python
    imagePullPolicy: Always
    command: ['sh', '-c', 'python -m pip install redis && python /tmp/redis_readiness_check.py']  
    volumeMounts:
      - name: redis-readiness-script
        mountPath: /tmp       
  volumes:
  - name: redis-readiness-script
    configMap:
      name: redis-readiness-script
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
{{- end }}