# helm install redis-video-pubsub bitnami/redis -n yanqizhang --set global.storageClass=local-storage --set master.persistence.size=10Gi --set replica.persistence.size=10Gi --set global.redis.password=redispubsub
# helm install redis-video-pubsub bitnami/redis \
# --set global.storageClass=local-storage \
# --set master.persistence.size=10Gi \
# --set replica.persistence.size=10Gi \
# --set global.redis.password=redispubsub
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: video-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-video-pubsub-master:6379
  - name: redisPassword
    value: redispubsub
  - name: redeliverInterval
    value: "0"
  # - name: queueDepth
  #   value: 1000