apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-socialnet-proxy
  labels:
    app: dapr-socialnet-proxy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: dapr-socialnet-proxy
  template:
    metadata:
      labels:
        app: dapr-socialnet-proxy
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-socialnet-proxy"
        dapr.io/app-port: "5005"
        dapr.io/app-protocol: "grpc"
        dapr.io/sidecar-listen-addresses: "0.0.0.0"
        dapr.io/http-max-request-size: "64"
        dapr.io/sidecar-image: "daprio/daprd:1.8.3"
        # dapr.io/config: "tracing"
        # dapr.io/log-level: "debug"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8084"
    spec:
      containers:
      - name: dapr-socialnet-proxy
        image: sailresearch/dapr-socialnet-proxy:latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "30"
        # ports:
        # - containerPort: 5005
        env:
        - name: PORT
          value: "5005"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: ADDRESS
          value: ":5005"
        - name: POST_STORE
          value: post-store