apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-ui-dashboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-ui-dashboard
        version: v1
    spec:
      containers:
      - name: ts-ui-dashboard
        image: kylinxiang/ts-ui-dashboard:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080