apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vpipe-video-store
  namespace: tmp
spec:
  metadata:
  - name: redisHost
    value: vipipe-redis-video-master:6379
  - name: redisPassword
    value: redisstore
  - name: keyPrefix
    value: none
  type: state.redis
  version: v1
